version: 2.1

jobs:
    prepare-dependencies:
        docker:
            - image: circleci/node:stretch
        working_directory: /mnt/ramdisk
        steps:
            - checkout
            - run:
                  name: Compute version number
                  command: echo "0.0.${CIRCLE_BUILD_NUM}-${CIRCLE_SHA1:0:7}" | tee version.txt
            - restore_cache:
                  keys:
                      - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: yarn install
                  command: yarn install --frozen-lockfile  
            - save_cache:
                  paths:
                      -  ~/.cache/yarn
                  key: yarn-packages-{{ checksum "yarn.lock" }}
            - store_artifacts:
                  path: yarn.lock
            - persist_to_workspace:
                  root: /mnt/ramdisk
                  paths:
                      - ./*

    build-production:
        docker:
            - image: circleci/node:stretch
        working_directory: /mnt/ramdisk
        environment:
          CACHE_IMAGE: brianoh1979/nodejs-circleci
          DOCKER_BUILDKIT: 1
        steps:
            - attach_workspace:
                  at: /mnt/ramdisk
            - setup_remote_docker:
                version: 19.03.13
                docker_layer_caching: false
            - run:
                name: Build from dockerfile
                command: |
                  docker build \
                    --cache-from $CACHE_IMAGE:latest \
                    --tag $CACHE_IMAGE:latest \
                    --build-arg BUILDKIT_INLINE_CACHE=1 \
                    "."
            - run: |
                  docker build -t $DOCKERHUB_USERNAME/circleci-demo-docker4 -t $DOCKERHUB_USERNAME/circleci-demo-docker4:$CIRCLE_SHA1 .
                  echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin 
                  docker push $DOCKERHUB_USERNAME/circleci-demo-docker4:$CIRCLE_SHA1
            - store_artifacts:
                  path: dist/server.js
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    test:
        docker:
            - image: circleci/node:stretch
        steps:
            - run: mkdir -p workspace
            - run: echo "Hello, world!" > workspace/echo-output
            - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is 
                # taken to be the root directory of the workspace.
                root: workspace
                # Must be relative path from root
                paths:
                  - echo-output

    test2:
        docker:
            - image: circleci/node:stretch
        steps:
            - attach_workspace:
                # Must be absolute path or relative path from working_directory
                at: /tmp/workspace

            - run: |
                if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
                  echo "It worked!";
                else
                  echo "Nope!"; exit 1
                fi

    test3:
        docker:
            - image: $DOCKERHUB_USERNAME/circleci-demo-docker4:$CIRCLE_SHA1
        steps:
            - run: echo "Hello from the custom image!!"

workflows:
    version: 2
    build-test-deploy:
        jobs:
            - prepare-dependencies
            - build-production:
                  requires:
                      - prepare-dependencies
            - test:
                  requires:
                      - prepare-dependencies
            - test2:
                  requires:
                      - test
            - test3:
                  requires:
                      - build-production
